### ISSUE TITLE
Please upload contents of milestone 2

### ISSUE THREAD

**Issue by kmes055** [kmes055/AutoDrawer#43]
Same as milestone 1, I need to know all of contributor's milestone status and some stuffs including photos about what you did.

Please upload your contents as comments

**Comment by hacking-racoon** [comment]
Because it was a mid-term exam period, as we decided, there were not much for Milestone.
So I have done other tasks.

1. Changing the Development Environment

I changed my development environment from Android Studio to React Native Expo To be compatible. So I studied React Native, and re-implemented modules.

2. Server Authentication

I was going to control access from external device by using Kakao Login API, 
However, Kakao API doesn't running in expo environment. 
I am solving this problem, but it is not working well...
I will use one of these solutions.
-  Expo eject
-  Web view open

3. File transfer

I re-implemented that in React Native Expo with expo-image-picker & expo-permissions.

To implement in RN Expo was much more easier than Android Studio.
However, I had some troubles on uploading, and that were solved.

-  problems  -
1. PHP settings ---- post_max_size, upload_max_size   value was too low
2. typo.
these error were solved by checking server log file. I learned a lot about that.

4. Idea sketch for connection with server.

However I still have technical difficulties for file_receive_transfer.
That is. 'How to know whether the conversion is done or not?'

I will solve this problem with async function. and socket network.

--------------
And.... i will send you images for PPT through your e-mail now.
Thank you!

**Comment by yellow2041** [comment]
이번주까지 완료한 부분
----------------------------
1. home화면 레이아웃 완료(메뉴바 제외)
2. 각각 버튼(Sketch, Pattern, Go!)과 연결되는 화면 완료
- - -
해결해야 할 것들
--------------------
1. 오른쪽 위 메뉴를 클릭하면 메뉴바가 슬라이딩 되면서 나타나도록 하고 싶은데 이 기능을 navigation중 createDrawerNavigation으로 구현하는데 이미 createStackNavigation을 쓴 상태임.
> 두 개의 함수?가 같은 메인 app파일 안에서 돌아가지 않아서 현재 함수로만 구현한 것을 class로 바꾸거나 구글링을 좀 더 해봐야 할 것 같음
2. Go!버튼을 누르면 사진을 변환할 때 나타나는 진행바에 진행률을 넣고 싶은데 어떤 방식으로 진행률을 받아와야 할 지 모르겠음
> 프로젝트가 더 진행되면 그 때 구현하기로.
3. 메인 화면 뜨기 전까지 잠깐 비출 로딩화면도 생각해야 함.

**Comment by kmes055** [comment]
Thanks
